---
jobs:
  build:
    docker:
      - image: docker:19.03.8
    working_directory: /app
    environment:
      - COMPOSE_FILE: docker-compose.build.yml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS 
      - run:
          name: Set Docker variables
          command: |
            set -e
            source docker.env
            printenv | grep DOCKER
      - run:
          name: Building image
          command: |
            set -e
            docker image build --pull -t $DOCKER_USER/$DOCKERIMG_NAME:$DOCKERIMG_VERSION .
      - run:
          name: Pushing image
          command: |
            set -e 
            docker image push $DOCKER_USER/$IMAGE_NAME:$IMAGE_VERSION
