---
jobs:
  build:
    docker:
      - image: docker:19.03.8
    working_directory: /app
    environment:
      - COMPOSE_FILE: docker-compose.build.yml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing Dependencies
          command: |
            set -x
            apk add --no-cache --no-progress py-pip python-dev libffi-dev openssl-dev gcc libc-dev make 
      - run:
          name: Installing docker-compose
          command: |
            set -x
            pip install docker-compose
      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS 
      - run:
          name: Building and Pushing images
          command: |
            set -e
            source docker.env
            docker-compose build --pull
            docker-compose push
