---
jobs:
  build:
    docker:
      - image: docker:19.03.8
    working_directory: /app
    environment:
      - COMPOSE_FILE: docker-compose.yml
    steps:
      - setup_remote_docker
      - run:
          name: Installing Dependencies
          command: |
            set -x
            apk add --no-cache --no-progress bash py-pip python-dev libffi-dev openssl-dev gcc libc-dev make curl
      - run:
          name: Installing docker-compose
          command: |
            set -x
            pip install docker-compose
      - run:
          name: Test Docker
          command: |
            set -x
            docker -v
            docker-compose -v
            docker run hello-world
            curl ifconfig.co

